# Generated by Django 2.0.3 on 2018-03-26 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('value', models.CharField(max_length=200, verbose_name='值')),
                ('description', models.CharField(max_length=100, verbose_name='描述')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=20)),
                ('url', models.CharField(blank=True, max_length=100, null=True)),
                ('icon', models.CharField(blank=True, max_length=20, null=True)),
                ('level', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='编码')),
                ('description', models.CharField(max_length=100, verbose_name='描述')),
            ],
        ),
        migrations.CreateModel(
            name='PermissionGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('description', models.CharField(max_length=100, verbose_name='描述')),
                ('enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('permissions', models.ManyToManyField(to='alleria.Permission', verbose_name='权限')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='用户名')),
                ('need_modify_password', models.BooleanField(default=True, verbose_name='需要修改密码')),
                ('email', models.CharField(blank=True, max_length=50, verbose_name='电子邮件')),
                ('is_active', models.BooleanField(choices=[(True, '启用'), (False, '禁用')], default=True, verbose_name='活动')),
                ('is_sa', models.BooleanField(choices=[(True, '是'), (False, '否')], default=False, verbose_name='超级管理员')),
                ('last_login_ip', models.CharField(blank=True, max_length=20, verbose_name='最近登录 IP')),
                ('roles', models.ManyToManyField(to='alleria.Role', verbose_name='角色')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='permission',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='alleria.PermissionGroup', verbose_name='组'),
        ),
    ]
