# Generated by Django 2.0.3 on 2018-03-29 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alleria', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dictionaryitem',
            name='value',
        ),
        migrations.AlterField(
            model_name='dictionaryitem',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='编码'),
        ),
        migrations.AlterField(
            model_name='dictionaryitem',
            name='name',
            field=models.CharField(max_length=20, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='dictionaryitem',
            name='order',
            field=models.IntegerField(default=0, verbose_name='顺序'),
        ),
        migrations.AlterField(
            model_name='dictionaryitem',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='alleria.DictionaryType', verbose_name='类型'),
        ),
    ]
