# Generated by Django 2.0.3 on 2018-03-26 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alleria', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='description',
        ),
    ]
