# Generated by Django 2.0.3 on 2018-04-09 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alleria', '0005_auto_20180408_2310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='line',
            new_name='lineno',
        ),
    ]
